### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by GabrielCrocker7** [NC1107/Bomb-Party-Bot#1]
I like the new version, however I liked the wordlist aspect of the previous one, because you could customize it. I feel like there should be a way to change the interval that it's typing during the game by clicking a button or something along the lines. And I don't know if it's possible, but even if it was separate from this one, a way to run ocr on the text and type it into the box, so that it could work automatically. These are just my thoughts, nothing really needs to be changed.

**Comment by NC1107** [comment]
Since I converted the files into one pyc file the word list is now inside of the main python file, this is a more optimized way that requires less file handling and can increase word search times. If you want I can send you the unpacked files and you can modify the word list from inside the py file or I can show you how to make it external again.
The typing speed isn't publicly accessible  since the file is compiled, but is easily modified if you wish for a different speed I can once again give you the unpacked files.
It's my mistake for calling it a bot since it's more of a helper but I don't plan on making it fully autonomous, although it's basically there anyway.
Thanks for the ideas/advice, if you want the files add me on the discord in my readmes. :)
